-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 14:07:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rdnl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rdnl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rdnl` DEFAULT CHARACTER SET utf8 ;
USE `rdnl` ;

-- -----------------------------------------------------
-- Table `rdnl`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Person` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Person` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Sofi` VARCHAR(45) NULL,
  `Email` VARCHAR(60) NULL,
  `Adress` VARCHAR(45) NULL,
  `Organisation` VARCHAR(45) NULL,
  `Password` VARCHAR(255) NULL,
  `Postalcode` VARCHAR(6) NULL,
  `Logintoken` VARCHAR(255) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Solutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Solutions` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Solutions` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Desc` TEXT NULL,
  `Title` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Request` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Request` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(70) NULL,
  `Desc` TEXT NULL,
  `InProgress` TINYINT NULL,
  `Solutions_Id` INT NOT NULL,
  `Progress_Step` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Request_Solutions1_idx` (`Solutions_Id` ASC),
  CONSTRAINT `fk_Request_Solutions1`
    FOREIGN KEY (`Solutions_Id`)
    REFERENCES `rdnl`.`Solutions` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Steps` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Steps` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(70) NULL,
  `Desc` TEXT NULL,
  `Activated` TINYINT NULL,
  `Comment` TINYINT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Organisation` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Organisation` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(70) NULL,
  `Adress` VARCHAR(45) NULL,
  `Phone` VARCHAR(10) NULL,
  `Website` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Request_has_Steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Request_has_Steps` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Request_has_Steps` (
  `Request_id` INT NOT NULL,
  `Steps_Id` INT NOT NULL,
  PRIMARY KEY (`Request_id`, `Steps_Id`),
  INDEX `fk_Request_has_Steps_Steps1_idx` (`Steps_Id` ASC),
  INDEX `fk_Request_has_Steps_Request_idx` (`Request_id` ASC),
  CONSTRAINT `fk_Request_has_Steps_Request`
    FOREIGN KEY (`Request_id`)
    REFERENCES `rdnl`.`Request` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_has_Steps_Steps1`
    FOREIGN KEY (`Steps_Id`)
    REFERENCES `rdnl`.`Steps` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Comments` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Comments` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Desc` TEXT NULL,
  `Commentscol` VARCHAR(45) NULL,
  `Person_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Comments_Person1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_Comments_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `rdnl`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Steps_has_Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Steps_has_Comments` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Steps_has_Comments` (
  `Steps_Id` INT NOT NULL,
  `Comments_Id` INT NOT NULL,
  PRIMARY KEY (`Steps_Id`, `Comments_Id`),
  INDEX `fk_Steps_has_Comments_Comments1_idx` (`Comments_Id` ASC),
  INDEX `fk_Steps_has_Comments_Steps1_idx` (`Steps_Id` ASC),
  CONSTRAINT `fk_Steps_has_Comments_Steps1`
    FOREIGN KEY (`Steps_Id`)
    REFERENCES `rdnl`.`Steps` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Steps_has_Comments_Comments1`
    FOREIGN KEY (`Comments_Id`)
    REFERENCES `rdnl`.`Comments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Organisation_has_Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Organisation_has_Person` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Organisation_has_Person` (
  `Organisation_Id` INT NOT NULL,
  `Person_id` INT NOT NULL,
  PRIMARY KEY (`Organisation_Id`, `Person_id`),
  INDEX `fk_Organisation_has_Person_Person1_idx` (`Person_id` ASC),
  INDEX `fk_Organisation_has_Person_Organisation1_idx` (`Organisation_Id` ASC),
  CONSTRAINT `fk_Organisation_has_Person_Organisation1`
    FOREIGN KEY (`Organisation_Id`)
    REFERENCES `rdnl`.`Organisation` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organisation_has_Person_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `rdnl`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Person_has_Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Person_has_Request` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Person_has_Request` (
  `Person_id` INT NOT NULL,
  `Request_id` INT NOT NULL,
  PRIMARY KEY (`Person_id`, `Request_id`),
  INDEX `fk_Person_has_Request_Request1_idx` (`Request_id` ASC),
  INDEX `fk_Person_has_Request_Person1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_Person_has_Request_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `rdnl`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_has_Request_Request1`
    FOREIGN KEY (`Request_id`)
    REFERENCES `rdnl`.`Request` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Invoice` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Desc` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  `Date` DATETIME NULL,
  `Paid` TINYINT NULL,
  `Due` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Steps_has_Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Steps_has_Invoice` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Steps_has_Invoice` (
  `Steps_Id` INT NOT NULL,
  `Invoice_Id` INT NOT NULL,
  `Amount` FLOAT NULL,
  PRIMARY KEY (`Steps_Id`, `Invoice_Id`),
  INDEX `fk_Steps_has_Invoice_Invoice1_idx` (`Invoice_Id` ASC),
  INDEX `fk_Steps_has_Invoice_Steps1_idx` (`Steps_Id` ASC),
  CONSTRAINT `fk_Steps_has_Invoice_Steps1`
    FOREIGN KEY (`Steps_Id`)
    REFERENCES `rdnl`.`Steps` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Steps_has_Invoice_Invoice1`
    FOREIGN KEY (`Invoice_Id`)
    REFERENCES `rdnl`.`Invoice` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Person_has_Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Person_has_Invoice` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Person_has_Invoice` (
  `Person_Id` INT NOT NULL,
  `Invoice_Id` INT NOT NULL,
  PRIMARY KEY (`Person_Id`, `Invoice_Id`),
  INDEX `fk_Person_has_Invoice_Invoice1_idx` (`Invoice_Id` ASC),
  INDEX `fk_Person_has_Invoice_Person1_idx` (`Person_Id` ASC),
  CONSTRAINT `fk_Person_has_Invoice_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `rdnl`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_has_Invoice_Invoice1`
    FOREIGN KEY (`Invoice_Id`)
    REFERENCES `rdnl`.`Invoice` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdnl`.`Steps_has_Organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rdnl`.`Steps_has_Organisation` ;

CREATE TABLE IF NOT EXISTS `rdnl`.`Steps_has_Organisation` (
  `Steps_Id` INT NOT NULL,
  `Organisation_Id` INT NOT NULL,
  PRIMARY KEY (`Steps_Id`, `Organisation_Id`),
  INDEX `fk_Steps_has_Organisation_Organisation1_idx` (`Organisation_Id` ASC),
  INDEX `fk_Steps_has_Organisation_Steps1_idx` (`Steps_Id` ASC),
  CONSTRAINT `fk_Steps_has_Organisation_Steps1`
    FOREIGN KEY (`Steps_Id`)
    REFERENCES `rdnl`.`Steps` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Steps_has_Organisation_Organisation1`
    FOREIGN KEY (`Organisation_Id`)
    REFERENCES `rdnl`.`Organisation` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
